[package]
name = "terminartist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
math="0.1.0"

# set environment variables
[profile.release]
RUST_BACKTRACE=1